local M = {}

function M.set(palette)
	local set = vim.api.nvim_set_hl

	local groups = {
		Conceal = { fg = palette.gray3 },
		CurSearch = { link = "Cursor" },
		Search = { fg = palette.bg, bg = palette.gray2 },
		IncSearch = { link = "Cursor" },
		Substitute = { link = "Search" },
		Cursor = { fg = palette.bg, bg = palette.fg },
		TermCursor = { link = "Cursor" },
		CursorLine = { bg = palette.gray1 },
		CursorColumn = { link = "CursorLine" },
		Directory = { fg = palette.gray6 },
		OkMsg = { fg = palette.fg },
		WarningMsg = { fg = palette.gray5 },
		ErrorMsg = { fg = palette.gray4 },
		StderrMsg = { link = "ErrorMsg" },
		WinSeperator = { link = "Normal" },
		LineNr = { link = "Conceal" },
		CursorLineNr = { link = "Cursor" },
		MatchParen = { link = "Cursor" },
		MsgArea = { link = "Normal" },
		Normal = { fg = palette.fg, bg = palette.bg },
		Pmenu = { link = "Normal" },
		PmenuSel = { link = "Cursor" },
		PmenuThumb = { link = "Cursor" },
		PmenuBorder = { link = "WinSeperator" },
		StatusLine = { link = "Normal" },
		StatusLineTerm = { link = "StatusLine" },
		Visual = { bg = palette.gray1 },
		Whitespace = { link = "Conceal" },

		Comment = { link = "Whitespace" },
		Constant = { fg = palette.yellow },
		String = { fg = palette.lyellow },
		Boolean = { link = "Statement" },
		Identifier = { fg = palette.gray6 },
		Function = { fg = palette.gray5 }, -- this is a comment
		Statement = { fg = palette.blue },
		Operator = { fg = palette.fg },
		PreProc = { link = "Statement" },
		Type = { link = "Statement" },
		Special = { link = "Operator" },
		SpecialChar = { fg = palette.yellow },
		Tag = { link = "Function" },
		Todo = { fg = palette.lyellow, bold = true },
		Added = { fg = palette.fg },
		Changed = { fg = palette.gray3 },
		Removed = { fg = palette.fg },

		["@lsp.type.class"] = { link = "Type" },
		["@lsp.type.comment"] = { link = "Comment" },
		["@lsp.type.decorator"] = { link = "" },
		["@lsp.type.enum"] = { link = "Type" },
		["@lsp.type.enumMember"] = { link = "Identifier" },
		["@lsp.type.event"] = { link = "" },
		["@lsp.type.function"] = { link = "Function" },
		["@lsp.type.interface"] = { link = "Type" },
		["@lsp.type.keyword"] = { link = "Statement" },
		["@lsp.type.macro"] = { link = "Function" },
		["@lsp.type.method"] = { link = "Function" },
		["@lsp.type.modifier"] = { link = "Statement" },
		["@lsp.type.namespace"] = { link = "Statement" },
		["@lsp.type.number"] = { link = "Number" },
		["@lsp.type.operator"] = { link = "Operator" },
		["@lsp.type.parameter"] = { link = "Identifier" },
		["@lsp.type.property"] = { link = "Identifier" },
		["@lsp.type.regexp"] = { link = "SpecialChar" },
		["@lsp.type.string"] = { link = "String" },
		["@lsp.type.struct"] = { link = "Type" },
		["@lsp.type.type"] = { link = "Type" },
		["@lsp.type.typeParameter"] = { link = "Identifier" },
		["@lsp.type.variable"] = { link = "Identifier" },

		DiagnosticError = { link = "ErrorMsg" },
		DiagnosticWarn = { link = "WarningMsg" },
		DiagnosticInfo = { link = "Normal" },
		DiagnosticHint = { link = "WarningMsg" },
		DiagnosticOk = { link = "OkMsg" },
		DiagnositcError = { link = "DiagnosticError" },
		DiagnositcWarn = { link = "DiagnosticWarn" },
		DiagnositcInfo = { link = "DiagnosticInfo" },
		DiagnositcHint = { link = "DiagnosticHint" },
		DiagnositcOk = { link = "DiagnosticOk" },
		DiagnositcVirtualTextError = { link = "DiagnosticError" },
		DiagnositcVirtualTextWarn = { link = "DiagnosticWarn" },
		DiagnositcVirtualTextInfo = { link = "DiagnosticInfo" },
		DiagnositcVirtualTextHint = { link = "DiagnosticHint" },
		DiagnositcVirtualTextOk = { link = "DiagnosticOk" },
		DiagnositcVirtualLinesError = { link = "DiagnosticError" },
		DiagnositcVirtualLinesWarn = { link = "DiagnosticWarn" },
		DiagnositcVirtualLinesInfo = { link = "DiagnosticInfo" },
		DiagnositcVirtualLinesHint = { link = "DiagnosticHint" },
		DiagnositcVirtualLinesOk = { link = "DiagnosticOk" },
		DiagnositcFloatingError = { link = "DiagnosticError" },
		DiagnositcFloatingWarn = { link = "DiagnosticWarn" },
		DiagnositcFloatingInfo = { link = "DiagnosticInfo" },
		DiagnositcFloatingHint = { link = "DiagnosticHint" },
		DiagnositcFloatingOk = { link = "DiagnosticOk" },
		DiagnositcSignError = { link = "DiagnosticError" },
		DiagnositcSignWarn = { link = "DiagnosticWarn" },
		DiagnositcSignInfo = { link = "DiagnosticInfo" },
		DiagnositcSignHint = { link = "DiagnosticHint" },
		DiagnositcSignOk = { link = "DiagnosticOk" },
		DiagnositcUnderlineError = { undercurl = true },
		DiagnositcUnderlineWarn = { undercurl = true },
		DiagnositcUnderlineInfo = { undercurl = true },
		DiagnositcUnderlineHint = { undercurl = true },
		DiagnositcUnderlineOk = { undercurl = true },
	}

	for group, highlight in pairs(groups) do
		set(0, group, highlight)
	end
end

return M
