local palette = {
	bgray3 = "#6c6c74",
	bgray2 = "#4c5058",
	bgray1 = "#30303c",
	bblack = "#101420",
	black = "#202020",
	gray1 = "#3c3c3c",
	gray2 = "#585858",
	gray3 = "#747474",
	gray4 = "#909090",
	gray5 = "#acacac",
	gray6 = "#c8c8c8",
	white = "#e4e4e4",
	red = "#b07470",
	lred = "#d08080",
	green = "#849070",
	lgreen = "#98b090",
	yellow = "#c0b080",
	lyellow = "#d0c090",
	blue = "#6880a0",
	lblue = "#7490c0",
	magenta = "#b080a0",
	lmagenta = "#d098c8",
	cyan = "#68a0b0",
	lcyan = "#80bcd0",
}

local variants = {
	dark = {
		bg = palette.black,
		black = palette.black,
		gray1 = palette.gray1,
		gray2 = palette.gray2,
		gray3 = palette.gray3,
		gray4 = palette.gray4,
		gray5 = palette.gray5,
		gray6 = palette.gray6,
		white = palette.white,
		fg = palette.white,
		red = palette.red,
		lred = palette.lred,
		green = palette.green,
		lgreen = palette.lgreen,
		yellow = palette.yellow,
		lyellow = palette.lyellow,
		blue = palette.blue,
		lblue = palette.lblue,
		magenta = palette.magenta,
		lmagenta = palette.lmagenta,
		cyan = palette.cyan,
		lcyan = palette.lcyan,
	},
	["faux-dark"] = {
		bg = palette.bblack,
		black = palette.black,
		gray1 = palette.bgray1,
		gray2 = palette.bgray2,
		gray3 = palette.bgray3,
		gray4 = palette.gray4,
		gray5 = palette.gray5,
		gray6 = palette.gray6,
		white = palette.white,
		fg = palette.white,
		red = palette.red,
		lred = palette.lred,
		green = palette.green,
		lgreen = palette.lgreen,
		yellow = palette.yellow,
		lyellow = palette.lyellow,
		blue = palette.blue,
		lblue = palette.lblue,
		magenta = palette.magenta,
		lmagenta = palette.lmagenta,
		cyan = palette.cyan,
		lcyan = palette.lcyan,
	},
}

local M = {}

function M.get(variant)
	variant = variant or "dark"
	return variants[variant]
end

return M
